name: Racket parsing reproducer 

on:
  workflow_dispatch:
    branches: [ "master" ]

jobs:
  windows:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019, windows-2022]
        racket_version:
          - '8.10'
          - '8.11'

    name: ${{ matrix.os }}, Racket ${{ matrix.racket_version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Racket
        uses: Bogdanp/setup-racket@v1.10
        with:
          architecture: 'x64'
          distribution: 'full'
          version: ${{ matrix.racket_version }}

      - name: Show Racket version
        run: racket --version

      - name: test 49 args
        run: racket 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48

      - name: test 50 args
        run: racket 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49

